[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cubeconundrum1"
path = "src/cubeconundrum1.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
substring = "1.4.5"
